### ISSUE TITLE
Error CAT_NO_ROWS_FOUND: None on MacOS

### ISSUE THREAD

**Issue by ylaizet** [mesocentre-mcia/brocoli#23]
We tried upload and download on MacOS and end up with the following error:

`uploading (u'......./shorai1 044 non stimule\u0301 montage.tif',) to /IrodsPath.........//outputs macro
put ......./shorai1 044 non stimulé montage.tif /IrodsPath.........//outputs macro/ /IrodsPath.........//outputs macro/shorai1 044 non stimulé montage.tif
Traceback (most recent call last):
  File "build/bdist.macosx-10.11-intel/egg/brocoli/treewidget.py", line 28, in method_wrapper
    return method(self, *args, **kwargs)
  File "build/bdist.macosx-10.11-intel/egg/brocoli/treewidget.py", line 367, in upload
    self.catalog.upload_files(files, path))
  File "build/bdist.macosx-10.11-intel/egg/brocoli/progress_dialog.py", line 76, in progress_from_generator
    for p, n in generator:
  File "build/bdist.macosx-10.11-intel/egg/brocoli/irodscatalog.py", line 250, in upload_files
    for s in self._upload_files(files, path):
  File "build/bdist.macosx-10.11-intel/egg/brocoli/irodscatalog.py", line 278, in _upload_files
    self.dom.put(f, irods_path, **options)
  File "/Library/Python/2.7/site-packages/python_irodsclient-0.7.0-py2.7.egg/irods/manager/data_object_manager.py", line 65, in put
    with open(file, 'rb') as f, self.open(obj, 'w', **options) as o:
  File "/Library/Python/2.7/site-packages/python_irodsclient-0.7.0-py2.7.egg/irods/manager/data_object_manager.py", line 146, in open
    desc = conn.recv().int_info
  File "/Library/Python/2.7/site-packages/python_irodsclient-0.7.0-py2.7.egg/irods/connection.py", line 91, in recv
    raise get_exception_by_code(msg.int_info)
CAT_NO_ROWS_FOUND: None`

**Comment by pigay** [comment]
I think this is a portabililty issue of python-irodsclient on MacOS. Hopefully, it has been fixed in https://github.com/irods/python-irodsclient/issues/104

You may try to upgrade your python-irodsclient to the github master branch with pip to check the fix.
Please tell if you try it.

Thanks for reporting.

**Comment by pigay** [comment]
You may try with the following:
`pip install --upgrade https://github.com/irods/python-irodsclient/archive/0e4a5be0918519f839670ec882420e7e4ee4f03d.zip`

**Comment by pigay** [comment]
python-irodsclient version 0.8.0 was released, which should fix the bug if you upgrade.
